version: "3.2"
services:
  backend: 
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '5050:5050'  
    volumes:
      - /backdir/node_modules
      - ./backend/src:/backdir/src
  frontend:
    build:
      context: ./wobbl
      dockerfile: ./Dockerfile
    volumes:
      - /frontdir/node_modules
      - ./wobbl:/frontdir
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
